[package]
name = "knull"
version = "2.1.0"
edition = "2024"
entry = "examples/hello_world.knull"
authors = ["4fqr"]
license = "MIT OR Apache-2.0"
desc = "The Knull programming language"
repository = "https://github.com/4fqr/knull"

[dependencies]

[dev-dependencies]
