; Knull compiled program
; Generated by knullc

section .text
    global _start

_start:
    call main
    mov rdi, rax
    mov rax, 60
    syscall

main:
    push rbp
    mov rbp, rsp
    pop rax
    lea rax, [rel str_1]
str_1: db "Hello, World!", 0
    pop rbp
    xor rax, rax
    ret

